### ISSUE TITLE
Add import modules for mangas

### ISSUE THREAD

**Issue by IkariTyux** [onmyshelf/onmyshelf#71]
Re,
Here are 2 french websites where you can find information on Manga and Anime.
- [Manga News](https://www.nautiljon.com/mangas/fullmetal+alchemist.html)
- [Nautiljon](https://www.manga-news.com/index.php/serie/FullMetal-Alchemist)

I believe it would be nice to have a module for them.

**Comment by pruje** [comment]
Hi,
Unfortunately, Nautiljon cannot be parsed because it uses some complex AJAX requests to Google.
I'll implement Manga News as an external module and add new "comics" collection template that can be used for any comics/mangas.

**Comment by pruje** [comment]
Hi,

You can test the next release 1.3.0 RC 1 from the nightly builds.
From this version, you can create (or update) a collection with type "comics".
Then install this module: https://gitlab.com/onmyshelf/modules/import/manga-news

Tell me if you still have issues. This issue can be re-opened if needed.
